/*
SpaceTraders API

Testing DataAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spacetraderssdk

import (
	"context"
	"testing"

	openapiclient "github.com/lwalthert/spacetraderssdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_spacetraderssdk_DataAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DataAPIService GetSupplyChain", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DataAPI.GetSupplyChain(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
