/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

API version: 2.3.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spacetraderssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSupplyChain200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSupplyChain200Response{}

// GetSupplyChain200Response struct for GetSupplyChain200Response
type GetSupplyChain200Response struct {
	Data GetSupplyChain200ResponseData `json:"data"`
}

type _GetSupplyChain200Response GetSupplyChain200Response

// NewGetSupplyChain200Response instantiates a new GetSupplyChain200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSupplyChain200Response(data GetSupplyChain200ResponseData) *GetSupplyChain200Response {
	this := GetSupplyChain200Response{}
	this.Data = data
	return &this
}

// NewGetSupplyChain200ResponseWithDefaults instantiates a new GetSupplyChain200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSupplyChain200ResponseWithDefaults() *GetSupplyChain200Response {
	this := GetSupplyChain200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetSupplyChain200Response) GetData() GetSupplyChain200ResponseData {
	if o == nil {
		var ret GetSupplyChain200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetSupplyChain200Response) GetDataOk() (*GetSupplyChain200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetSupplyChain200Response) SetData(v GetSupplyChain200ResponseData) {
	o.Data = v
}

func (o GetSupplyChain200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSupplyChain200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetSupplyChain200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSupplyChain200Response := _GetSupplyChain200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSupplyChain200Response)

	if err != nil {
		return err
	}

	*o = GetSupplyChain200Response(varGetSupplyChain200Response)

	return err
}

type NullableGetSupplyChain200Response struct {
	value *GetSupplyChain200Response
	isSet bool
}

func (v NullableGetSupplyChain200Response) Get() *GetSupplyChain200Response {
	return v.value
}

func (v *NullableGetSupplyChain200Response) Set(val *GetSupplyChain200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSupplyChain200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSupplyChain200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSupplyChain200Response(val *GetSupplyChain200Response) *NullableGetSupplyChain200Response {
	return &NullableGetSupplyChain200Response{value: val, isSet: true}
}

func (v NullableGetSupplyChain200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSupplyChain200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


