/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

API version: 2.3.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spacetraderssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetShipModules200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetShipModules200Response{}

// GetShipModules200Response struct for GetShipModules200Response
type GetShipModules200Response struct {
	Data []ShipModule `json:"data"`
}

type _GetShipModules200Response GetShipModules200Response

// NewGetShipModules200Response instantiates a new GetShipModules200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetShipModules200Response(data []ShipModule) *GetShipModules200Response {
	this := GetShipModules200Response{}
	this.Data = data
	return &this
}

// NewGetShipModules200ResponseWithDefaults instantiates a new GetShipModules200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetShipModules200ResponseWithDefaults() *GetShipModules200Response {
	this := GetShipModules200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetShipModules200Response) GetData() []ShipModule {
	if o == nil {
		var ret []ShipModule
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetShipModules200Response) GetDataOk() ([]ShipModule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetShipModules200Response) SetData(v []ShipModule) {
	o.Data = v
}

func (o GetShipModules200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetShipModules200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetShipModules200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetShipModules200Response := _GetShipModules200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetShipModules200Response)

	if err != nil {
		return err
	}

	*o = GetShipModules200Response(varGetShipModules200Response)

	return err
}

type NullableGetShipModules200Response struct {
	value *GetShipModules200Response
	isSet bool
}

func (v NullableGetShipModules200Response) Get() *GetShipModules200Response {
	return v.value
}

func (v *NullableGetShipModules200Response) Set(val *GetShipModules200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetShipModules200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetShipModules200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetShipModules200Response(val *GetShipModules200Response) *NullableGetShipModules200Response {
	return &NullableGetShipModules200Response{value: val, isSet: true}
}

func (v NullableGetShipModules200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetShipModules200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


