/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

API version: 2.3.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spacetraderssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSupplyChain200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSupplyChain200ResponseData{}

// GetSupplyChain200ResponseData struct for GetSupplyChain200ResponseData
type GetSupplyChain200ResponseData struct {
	ExportToImportMap map[string][]string `json:"exportToImportMap"`
}

type _GetSupplyChain200ResponseData GetSupplyChain200ResponseData

// NewGetSupplyChain200ResponseData instantiates a new GetSupplyChain200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSupplyChain200ResponseData(exportToImportMap map[string][]string) *GetSupplyChain200ResponseData {
	this := GetSupplyChain200ResponseData{}
	this.ExportToImportMap = exportToImportMap
	return &this
}

// NewGetSupplyChain200ResponseDataWithDefaults instantiates a new GetSupplyChain200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSupplyChain200ResponseDataWithDefaults() *GetSupplyChain200ResponseData {
	this := GetSupplyChain200ResponseData{}
	return &this
}

// GetExportToImportMap returns the ExportToImportMap field value
func (o *GetSupplyChain200ResponseData) GetExportToImportMap() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}

	return o.ExportToImportMap
}

// GetExportToImportMapOk returns a tuple with the ExportToImportMap field value
// and a boolean to check if the value has been set.
func (o *GetSupplyChain200ResponseData) GetExportToImportMapOk() (*map[string][]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportToImportMap, true
}

// SetExportToImportMap sets field value
func (o *GetSupplyChain200ResponseData) SetExportToImportMap(v map[string][]string) {
	o.ExportToImportMap = v
}

func (o GetSupplyChain200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSupplyChain200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exportToImportMap"] = o.ExportToImportMap
	return toSerialize, nil
}

func (o *GetSupplyChain200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exportToImportMap",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSupplyChain200ResponseData := _GetSupplyChain200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSupplyChain200ResponseData)

	if err != nil {
		return err
	}

	*o = GetSupplyChain200ResponseData(varGetSupplyChain200ResponseData)

	return err
}

type NullableGetSupplyChain200ResponseData struct {
	value *GetSupplyChain200ResponseData
	isSet bool
}

func (v NullableGetSupplyChain200ResponseData) Get() *GetSupplyChain200ResponseData {
	return v.value
}

func (v *NullableGetSupplyChain200ResponseData) Set(val *GetSupplyChain200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSupplyChain200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSupplyChain200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSupplyChain200ResponseData(val *GetSupplyChain200ResponseData) *NullableGetSupplyChain200ResponseData {
	return &NullableGetSupplyChain200ResponseData{value: val, isSet: true}
}

func (v NullableGetSupplyChain200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSupplyChain200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


