/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

API version: 2.3.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spacetraderssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstallShipModule201ResponseDataTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallShipModule201ResponseDataTransaction{}

// InstallShipModule201ResponseDataTransaction struct for InstallShipModule201ResponseDataTransaction
type InstallShipModule201ResponseDataTransaction struct {
	WaypointSymbol string `json:"waypointSymbol"`
	ShipSymbol string `json:"shipSymbol"`
	TradeSymbol string `json:"tradeSymbol"`
	TotalPrice int32 `json:"totalPrice"`
	Timestamp string `json:"timestamp"`
}

type _InstallShipModule201ResponseDataTransaction InstallShipModule201ResponseDataTransaction

// NewInstallShipModule201ResponseDataTransaction instantiates a new InstallShipModule201ResponseDataTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallShipModule201ResponseDataTransaction(waypointSymbol string, shipSymbol string, tradeSymbol string, totalPrice int32, timestamp string) *InstallShipModule201ResponseDataTransaction {
	this := InstallShipModule201ResponseDataTransaction{}
	this.WaypointSymbol = waypointSymbol
	this.ShipSymbol = shipSymbol
	this.TradeSymbol = tradeSymbol
	this.TotalPrice = totalPrice
	this.Timestamp = timestamp
	return &this
}

// NewInstallShipModule201ResponseDataTransactionWithDefaults instantiates a new InstallShipModule201ResponseDataTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallShipModule201ResponseDataTransactionWithDefaults() *InstallShipModule201ResponseDataTransaction {
	this := InstallShipModule201ResponseDataTransaction{}
	return &this
}

// GetWaypointSymbol returns the WaypointSymbol field value
func (o *InstallShipModule201ResponseDataTransaction) GetWaypointSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WaypointSymbol
}

// GetWaypointSymbolOk returns a tuple with the WaypointSymbol field value
// and a boolean to check if the value has been set.
func (o *InstallShipModule201ResponseDataTransaction) GetWaypointSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WaypointSymbol, true
}

// SetWaypointSymbol sets field value
func (o *InstallShipModule201ResponseDataTransaction) SetWaypointSymbol(v string) {
	o.WaypointSymbol = v
}

// GetShipSymbol returns the ShipSymbol field value
func (o *InstallShipModule201ResponseDataTransaction) GetShipSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipSymbol
}

// GetShipSymbolOk returns a tuple with the ShipSymbol field value
// and a boolean to check if the value has been set.
func (o *InstallShipModule201ResponseDataTransaction) GetShipSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipSymbol, true
}

// SetShipSymbol sets field value
func (o *InstallShipModule201ResponseDataTransaction) SetShipSymbol(v string) {
	o.ShipSymbol = v
}

// GetTradeSymbol returns the TradeSymbol field value
func (o *InstallShipModule201ResponseDataTransaction) GetTradeSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradeSymbol
}

// GetTradeSymbolOk returns a tuple with the TradeSymbol field value
// and a boolean to check if the value has been set.
func (o *InstallShipModule201ResponseDataTransaction) GetTradeSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeSymbol, true
}

// SetTradeSymbol sets field value
func (o *InstallShipModule201ResponseDataTransaction) SetTradeSymbol(v string) {
	o.TradeSymbol = v
}

// GetTotalPrice returns the TotalPrice field value
func (o *InstallShipModule201ResponseDataTransaction) GetTotalPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value
// and a boolean to check if the value has been set.
func (o *InstallShipModule201ResponseDataTransaction) GetTotalPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPrice, true
}

// SetTotalPrice sets field value
func (o *InstallShipModule201ResponseDataTransaction) SetTotalPrice(v int32) {
	o.TotalPrice = v
}

// GetTimestamp returns the Timestamp field value
func (o *InstallShipModule201ResponseDataTransaction) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *InstallShipModule201ResponseDataTransaction) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *InstallShipModule201ResponseDataTransaction) SetTimestamp(v string) {
	o.Timestamp = v
}

func (o InstallShipModule201ResponseDataTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallShipModule201ResponseDataTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["waypointSymbol"] = o.WaypointSymbol
	toSerialize["shipSymbol"] = o.ShipSymbol
	toSerialize["tradeSymbol"] = o.TradeSymbol
	toSerialize["totalPrice"] = o.TotalPrice
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *InstallShipModule201ResponseDataTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"waypointSymbol",
		"shipSymbol",
		"tradeSymbol",
		"totalPrice",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstallShipModule201ResponseDataTransaction := _InstallShipModule201ResponseDataTransaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstallShipModule201ResponseDataTransaction)

	if err != nil {
		return err
	}

	*o = InstallShipModule201ResponseDataTransaction(varInstallShipModule201ResponseDataTransaction)

	return err
}

type NullableInstallShipModule201ResponseDataTransaction struct {
	value *InstallShipModule201ResponseDataTransaction
	isSet bool
}

func (v NullableInstallShipModule201ResponseDataTransaction) Get() *InstallShipModule201ResponseDataTransaction {
	return v.value
}

func (v *NullableInstallShipModule201ResponseDataTransaction) Set(val *InstallShipModule201ResponseDataTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallShipModule201ResponseDataTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallShipModule201ResponseDataTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallShipModule201ResponseDataTransaction(val *InstallShipModule201ResponseDataTransaction) *NullableInstallShipModule201ResponseDataTransaction {
	return &NullableInstallShipModule201ResponseDataTransaction{value: val, isSet: true}
}

func (v NullableInstallShipModule201ResponseDataTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallShipModule201ResponseDataTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


